version: "3.5"

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: user123
      MONGO_INITDB_ROOT_PASSWORD: user123

    volumes:
      - 'mongodb_data:/data/db'
      - 'mongodb_config:/data/configdb'

  # mongo-express:
  #   image: mongo-express
  #   container_name: mongo-express
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: user123
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: user123
  #     ME_CONFIG_MONGODB_SERVER: mongo
  #     ME_CONFIG_MONGODB_PORT: "27017"
  #   ports:
  #     - "8081:8081"

  #   depends_on:
  #     - mongo

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local
